name: Base Image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mittwillson/darwinia-builder-rust

jobs:
  release:
    name: Release Base Image
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: "mittwillson"
          password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Setup QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Setup Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      
      - uses: actions/checkout@v2

      - name: Build Image && Publish
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} -f Dockerfile.base --push .

      # - name: Build Image && Publish
      #   run: docker buildx build --platform linux/arm64 -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} -f Dockerfile.base --push .
