name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '分支版本'
        required: true

env:
  REGISTRY: ghcr.io
  TAG: ${{ github.event.inputs.tag }}
  IMAGE_NAME: mittwillson/darwinia-image
  ORIGIN_REPO: darwinia-network/darwinia

jobs:
  release:
    name: Release Darwinia Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Login Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/checkout@v2

      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.ORIGIN_REPO }}
          ref: ${{ env.TAG }}
          fetch-depth: 1
          path: 'darwinia'

      - name: Build ARM64 Package
        run: |
          cd darwinia && git apply 0001-fix-arm64-build.patch && cd ../
          docker buildx build --platform linux/arm64 -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .

      - name: Publish
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}